// Optional browser regression. Requires Playwright and an installed Chromium browser.
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {EXAMPLE,LETTERS,splitExpected,PLATFORMS} from '../../public/assets/framework.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const root=resolve('public');
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root+'/')){res.writeHead(403);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css'})[extname(file)]||'text/plain');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({acceptDownloads:true});const url=`http://127.0.0.1:${server.address().port}`;
let generationCalls=0,dialogs=0;const errors=[];
context.on('page',p=>{p.on('pageerror',e=>errors.push(e.message));p.on('crash',()=>errors.push('renderer crashed'));p.on('dialog',async d=>{dialogs++;await d.dismiss();});});
await context.route('**/.netlify/functions/gemini-proxy',async route=>{const data=route.request().postDataJSON();if(data.action==='generate'){generationCalls++;await new Promise(r=>setTimeout(r,350));await route.fulfill({json:{copy:generationCalls===1?'Try the new oat-milk latte Monday for $4.50.':'Between classes? Try the new oat-milk latte Monday for $4.50.',claims:[{claim:'The latte costs $4.50.',source:'Approved fact sheet: price'}]}});}else{const elements=Object.fromEntries(LETTERS.map(k=>[k,{score:2,evidence:data.brief[k].slice(0,20),feedback:'Matches the rubric.'}]));await route.fulfill({json:{elements,total:10,greenlit:true,approval:'mock-approval',rubricVersion:'BRIEF-1.0',scenario:data.scenario,model:'mock',suspectedInjection:false}});}});
async function grade(p){await p.locator('#grade').click();await p.waitForFunction(()=>!document.querySelector('#generate').disabled);}
try{
 let page=await context.newPage();await page.goto(url);await page.locator('#outputType').selectOption('organic');for(const k of ['B','R','I','F'])await page.locator('#field-'+k).fill(EXAMPLE[k]);await page.locator('#field-E-objective').fill(splitExpected(EXAMPLE.E).objective);await grade(page);await page.locator('#generate').click();await page.waitForFunction(()=>!document.querySelector('#reviewFields').disabled);
 await page.locator('#claim-0-evidence').fill('The supplied fact sheet approves the $4.50 price.');await page.locator('#decision-0').selectOption('verified');await page.locator('#fit').fill('This invitation addresses students looking for a break between classes.');await page.locator('#finalCopy').fill('Need a coffee break? Try the new oat-milk latte Monday for $4.50.');await page.locator('#explanation').fill('I added an opening about a coffee break. This fits the student audience and makes the invitation more relevant.');await page.locator('#confirmed').check();await page.locator('#complete').click();assert(await page.locator('#completion').isVisible());
 // Simulate an earlier build's record, then reopen in the same browser profile.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('brief-trainer-v1'));delete s.scenario;delete s.eParts;delete s.feedback;delete s.grade.scenario;delete s.draft.scenario;localStorage.setItem('brief-trainer-v1',JSON.stringify(s));});await page.close();page=await context.newPage();await page.goto(url);assert((await page.locator('#originalDraft').innerText()).includes('Monday'));assert(await page.locator('#completion').isVisible());
 await page.locator('#field-E-objective').fill('Encourage students to visit Campus Corner Coffee during launch week.');await grade(page);await page.locator('#generate').click();assert(await page.locator('#replaceDraftPrompt').isVisible());assert.equal(generationCalls,1);assert.equal(await page.evaluate(()=>2+2),4);assert.equal(dialogs,0);
 await page.locator('#keepDraft').click();assert.equal(generationCalls,1);assert((await page.locator('#finalCopy').inputValue()).startsWith('Need a coffee break?'));
 await page.locator('#generate').click();await page.locator('#replaceDraft').click();assert.equal(await page.locator('#generate').innerText(),'Generating…');assert(await page.locator('#generationProgress').isVisible());assert.equal(await page.evaluate(()=>2+2),4);await page.waitForFunction(()=>!document.querySelector('#reviewFields').disabled);
 assert.equal(generationCalls,2);const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('brief-trainer-v1')));assert.equal(saved.drafts.length,1);assert(saved.drafts[0].review.finalCopy.startsWith('Need a coffee break?'));assert.equal(saved.review.completedAt,null);assert.equal(saved.review.explanation,'');
 await page.reload();assert((await page.locator('#originalDraft').innerText()).startsWith('Between classes?'));const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download').click()]);const html=await readFile(await download.path(),'utf8');assert(html.includes('Need a coffee break?'));assert(html.includes('Between classes?'));assert(!html.includes('mock-approval'));const objective=await page.locator('#field-E-objective').inputValue();assert.equal(await page.locator('#platform option').count(),5);for(const [id,spec] of Object.entries(PLATFORMS)){await page.locator('#platform').selectOption(id);assert.equal(await page.locator('#field-E-objective').inputValue(),objective);assert((await page.locator('#field-E-format').inputValue()).includes(spec.label));assert(await page.locator('#generate').isDisabled());await page.locator('#outputType').selectOption('ad');assert((await page.locator('#field-E-format').inputValue()).includes('headline'));await page.locator('#outputType').selectOption('organic');}await page.reload();assert.equal(await page.locator('#platform').inputValue(),'linkedin');await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(dialogs,0);assert.deepEqual(errors,[]);
 console.log('PASS: carried-over older session, fresh grade, inline replacement, cancel, progress, regeneration, archived review, refresh, download, five platform formats, objective preservation, and mobile; no native dialogs.');
}finally{await context.close();await browser.close();await new Promise(r=>server.close(r));}
